pipeline {
    agent any

    environment {
        PYTHON = "C:\\Program Files\\Python311\\python.exe"
        VENV = "venv"
    }

    stages {

        stage('Verify Python') {
            steps {
                bat """
                "%PYTHON%" --version
                """
            }
        }

        stage('Setup Virtual Environment') {
            steps {
                bat """
                "%PYTHON%" -m venv %VENV%
                call %VENV%\\Scripts\\activate
                python -m pip install --upgrade pip setuptools wheel
                """
            }
        }

        stage('Install Dependencies') {
            steps {
                bat """
                call %VENV%\\Scripts\\activate
                pip install -r requirements.txt
                """
            }
        }

        stage('Train Model') {
            steps {
                bat """
                call %VENV%\\Scripts\\activate
                python -m src.pipeline.train_pipeline
                """
            }
        }

        stage('Predict') {
            steps {
                bat """
                call %VENV%\\Scripts\\activate
                python -m src.pipeline.predict_pipeline
                """
            }
        }
    }
}
