pipeline {
    agent any

    environment {
        PYTHON_311 = "C:\\Program Files\\Python311\\python.exe"
        VENV_DIR = "venv"
    }

    stages {
        stage('Setup Environment') {
            steps {
                bat '''
                echo Using Python:
                "%PYTHON_311%" --version

                if not exist %VENV_DIR% (
                    "%PYTHON_311%" -m venv %VENV_DIR%
                )

                %VENV_DIR%\\Scripts\\python -m pip install --upgrade pip setuptools wheel
                %VENV_DIR%\\Scripts\\pip install -r requirements.txt
                '''
            }
        }

        stage('Train Model') {
            steps {
                bat '''
                %VENV_DIR%\\Scripts\\python -m src.pipeline.train_pipeline
                '''
            }
        }

        stage('Predict') {
            steps {
                bat '''
                %VENV_DIR%\\Scripts\\python -m src.pipeline.predict_pipeline
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'artifacts/**, logs/**', fingerprint: true
        }
    }
}
